spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/petapp
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

